import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono, Work_Sans } from "next/font/google"
import "./global.css"
import { AppClientLayout } from "./AppClientLayout"

const _geist = Geist({ subsets: ["latin"] })
const _geistMono = Geist_Mono({ subsets: ["latin"] })
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300","400", "500", "700"],
  variable: "--font-work-sans",
})

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="layout">
      <body className={`${workSans.className} font-sans antialiased`}>
        <AppClientLayout>{children}</AppClientLayout>
      </body>
    </html>
  )
}
   