import type React from "react"
import type { Metadata } from "next"
import { Geist, Geist_Mono, Work_Sans } from "next/font/google"
import { Analytics } from "@vercel/analytics/next"
import "./global.css"
import { InboxProvider } from "@/context/inbox-context"
import { UserProvider } from "@/context/userContext"
import { getNotificacionesByUsuario } from "@/services/Notificaciones.service"
import type { Notificacion } from "@/types/Notificaciones"
import { Suspense } from "react"
import { ProtectedRoute } from "@/components/ProtectedRoute"

const _geist = Geist({ subsets: ["latin"] })
const _geistMono = Geist_Mono({ subsets: ["latin"] })
const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-work-sans",
})

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const idUsuarioActual = 3
  const initialNotifications: Notificacion[] = await getNotificacionesByUsuario(idUsuarioActual)

  return (
    <html lang="en">
      <body className={`${workSans.className} font-sans antialiased`}>
        <Suspense>
          <UserProvider>
            <InboxProvider>
              <ProtectedRoute>{children}</ProtectedRoute>
            </InboxProvider>
          </UserProvider>
        </Suspense>
        <Analytics />
      </body>
    </html>
  )
}
